import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen bg-gray-500">
        <section className="flex justify-around">
          <div className="w-4/12 border border-white">
            Recycling
          </div>
          <div className="w-4/12 border border-white">
            Compost
          </div>
          <div className="w-4/12 border border-white">
            Trash
          </div>
        </section>
        
        <section className="grid grid-cols-1 place-items-center">
          <div className="bg-orange-500 px-2 py-1">
            shooter
          </div>
        </section>
      </main>
    </div>
  )
}
